# .github/workflows/flutter_ci.yaml

name: Flutter CI & Firebase Distribution

on:
  push:
    branches: [dev]

jobs:
  build:
    name: Build and Distribute APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
      
      - name: Write app.env.dart from secret
        run: |
          mkdir -p lib/env
          echo "${{ secrets.APP_ENV_FILE }}" > lib/env/app.env.dart

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      ############################
      ## ANDROID BUILD SECTION ##
      ############################

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload Android to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_ANDROID_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: Testers
          file: build/app/outputs/flutter-apk/app-release.apk

      ########################
      ## iOS BUILD SECTION ##
      ########################

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.IOS_PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/app.mobileprovision

      - name: Set up certificate
        run: |
          echo "${{ secrets.IOS_CERTIFICATE_BASE64 }}" | base64 --decode > certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import certificate.p12 -k build.keychain -P "${{ secrets.IOS_CERTIFICATE_PASSWORD }}" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Build iOS IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload iOS to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_IOS_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: Testers
          file: build/ios/ipa/*.ipa
